name: dupquest
channels:
  - conda-forge
dependencies:
#  - nose
#  - coverage
#  - gcc
#  - cython
#  - numpy
#  - scipy
  - scikit-learn
#  - pyflann=1.8.5
#  - pyamg
#  - h5py
#  - plotly
#  - megaman
  - umap-learn
  - pkg-config
  - pandas=0.23.0
  - pip:
    - fuzzywuzzy
    - python-Levenshtein
    - minio
    - s3fs
#    - sklearn
#    - keras
    - nltk
    - msgpack<0.6.0
    - gensim
    - toolz
#    - cython>=0.27.3
#    - cvxopt>=1.2.0
#    - grakel-dev
    - dask[complete]
    - distributed
    - bokeh
    - matplotlib
#    - spacy<2.0.18
#    - joblib
#    - multiprocessing_on_dill
#    - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.0.0/en_core_web_lg-2.0.0.tar.gz