name: dupquest

dependencies:
  - pandas=0.23.0
  - pip:
    - fuzzywuzzy
    - python-Levenshtein
    - minio
    - s3fs
    - sklearn
    - keras
    - nltk
    - msgpack<0.6.0
    - spacy
    - joblib