name: dupquest

dependencies:
  - pandas=0.23.0
  - pip:
    - fuzzywuzzy
    - python-Levenshtein
    - minio
    - s3fs
    - sklearn
    - keras
    - nltk
    - msgpack<0.6.0
    - spacy<2.0.18
#    - joblib
    - multiprocessing_on_dill
#    - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.0.0/en_core_web_lg-2.0.0.tar.gz